name: update investments

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 20 * * *"

jobs:
  update_investments_sheet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: install modules
        run: yarn

      - name: setup google service account
        run: node setupGoogleService.js
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}

      - name: update stats
        run: node updateInv.js
        env:
          XC: ${{ secrets.XC }}
          SAM: ${{ secrets.SAM }}
          SHEETID: ${{ secrets.SHEETID }}
